# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-29 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 4, 29, 10, 54, 55, 859900, tzinfo=utc))),
                ('body', models.TextField()),
            ],
        ),
    ]
